title: "Roldan Eng Software - Desenvolvedor"
description: "Portf√≥lio de Roldan Eng Software"
theme: jekyll-theme-minimal
baseurl: "/roldan-eng-software"
url: "https://roldan-eng-software.github.io"
markdown: kramdown
exclude:
  - node_modules
  - dist
  - scripts
  - package-lock.json
